name: FMU-v5 scan-build

on:
  push:
    branches:
    - 'master'
    - 'fmu-v5-actions'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/render-se/px4-base:latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}
    - name: Run scan-build
      run: make scan-build
