name: SITL Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2019-10-24
    steps:
    - uses: actions/checkout@v1
    - name: SITL tests
      run: PX4_MAVSDK_TESTING=y DONT_RUN=1 make px4_sitl gazebo mavsdk_tests && test/mavsdk_tests/mavsdk_test_runner.py --verbose --speed-factor 20
